# Generated by Django 3.1.4 on 2020-12-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
