# Generated by Django 3.1.4 on 2020-12-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
